### ISSUE TITLE
Auto reconnecting not functional with 1.16 clients.

### ISSUE THREAD

**Issue by mibby** [AoElite/AutoReconnect#9] opened 2020-06-24 19:23 UTC
Waterfall dev 357 (BungeeCord Fork)
ViaVersion dev 411 (On BungeeCord)
AutoReconnect v1.2

Auto reconnecting does not seem to work with 1.16 clients. The clients immediately get disconnected instead of pending / idling for reconnect. 1.15.2 clients work fine and reconnect, 1.16.1 clients immediately close.

**Comment by PseudoResonance** [comment] 2020-06-24 21:24
I've pushed an updated version that supports the latest BungeeCord version.
[AutoReconnect-1.4.jar.zip](https://github.com/AoElite/AutoReconnect/files/4827956/AutoReconnect-1.4.jar.zip)

**Comment by vc606** [comment] 2020-07-02 05:50
> I've pushed an updated version that supports the latest BungeeCord version.
> [AutoReconnect-1.4.jar.zip](https://github.com/AoElite/AutoReconnect/files/4827956/AutoReconnect-1.4.jar.zip)

My server uses viaversion and ViaBackwards. This may cause 1.16 to fail to reconnect normally. Is there a solution?

**Comment by PseudoResonance** [comment] 2020-07-04 22:00
Are you running a 1.15 server with ViaVersion for 1.16 and ViaBackwards for older versions?
I've tested this running the latest version of PaperSpigot, ViaVersion and ViaBackwards with default configs and am unable to reproduce your issue. Please check the logs to see if there were any issues, otherwise I don't really know how to help you.

**Comment by PseudoResonance** [comment] 2020-09-21 04:51
No reply, so assuming issue is resolved.
1.16 support addressed in 302fbe01fde7ea83203e0a064b244cc0ab817a93

**Closed by PseudoResonance** 2020-09-21 04:51 UTC
